### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by matkoch**
That's the  official name :)

### CODE REVIEW

**Comment by mastorm** [comment]
If you want a Verified Jetbrains Employee role, just hit me up, ill get it figured out with staff ;)

**Comment by matkoch** [comment]
@mastorm thanks! :)

**Comment by matkoch** [comment]
@mastorm ah yeah, sure  :)

**Comment by matkoch** [comment]
@mastorm I actually also wanted  to ask you if you'd find a dedicated #jetbrains channel useful.. you know, so that people can ask questions directly... I would be glad to help :)

**Comment by mastorm** [comment]
We have #architecture-and-tooling, in which we usually dispute rider and Jetbrains stuff, but maybe we can set up a pingrole or something. We have worked with jetbrains for giveaways before, maybe ruby would be willing to do that. Ill bring it up with him :)

**Pull request merged**
